Repository fga-eps-mds/2019.2-ArBC, pull requests merged in 2019-09, with the labels that each got.

#19 Políticas do Projeto
  docs/mds/Documento_de_arquitetura.md
  docs/policies/branches.md
  docs/policies/commits.md
  docs/policies/issues.md
  docs/policies/pull_requests.md
Labels: EPS, documentation

#25 Ambiente de Desenvolvimento
  .browserslistrc
  .gitignore
  Dockerfile
  README.md
  babel.config.js
  docker-compose.yml
  package-lock.json
  package.json
  postcss.config.js
  public/favicon.ico
  public/img/icons/android-chrome-192x192.png
  public/img/icons/android-chrome-512x512.png
  public/img/icons/apple-touch-icon-120x120.png
  public/img/icons/apple-touch-icon-152x152.png
  public/img/icons/apple-touch-icon-180x180.png
  public/img/icons/apple-touch-icon-60x60.png
  public/img/icons/apple-touch-icon-76x76.png
  public/img/icons/apple-touch-icon.png
  public/img/icons/favicon-16x16.png
  public/img/icons/favicon-32x32.png
  public/img/icons/msapplication-icon-144x144.png
  public/img/icons/mstile-150x150.png
  public/img/icons/safari-pinned-tab.svg
  public/index.html
  public/manifest.json
  public/robots.txt
  src/App.vue
  src/assets/arara.svg
  src/assets/logo.png
  src/assets/yoda.svg
  src/components/HelloWorld.vue
  src/main.ts
  src/registerServiceWorker.ts
  src/router.ts
  src/shims-tsx.d.ts
  src/shims-vue.d.ts
  src/store.ts
  src/views/About.vue
  src/views/Home.vue
  tests/e2e/custom-assertions/elementCount.js
  tests/e2e/specs/test.js
  tests/unit/example.spec.ts
  tsconfig.json
  tslint.json
Labels: EPS, architect, devops

#27 Correção de vulnerabilidades do repositório.
  package-lock.json
Labels: devops, technical

#26 Elaboracao Documento de Arquitetura
  docs/imagens/documento_de_arquitetura/Diagrama_Caso_Uso_ArBC.jpeg
  docs/imagens/documento_de_arquitetura/Diagrama_Relações.jpeg
  docs/imagens/documento_de_arquitetura/vuex.png
  docs/mds/Documento_de_arquitetura.md
Labels: MDS, architect, devops, documentation, good first issue

#32 CÓDIGO DE CONDUTA
  CODE_OF_CONDUCT.md
Labels: EPS, documentation

#38 Estrutura Analítica do Projeto (EAP)
  docs/EAP.md
  docs/sprints/Planejamento-Sprint-0.md
  docs/sprints/Planejamento-Sprint-1.md
  docs/sprints/Planejamento-Sprint-2.md
Labels: EPS, documentation

#34 Integração com a câmera do usuário
  src/assets/yoda.svg
  src/components/Camera.vue
  src/components/HelloWorld.vue
  src/views/Home.vue
Labels: MDS, new feature, technical

#43 Integração Contínua
  .gitlab-ci.yml
  Dockerfile
  docker-compose.yml
Labels: EPS, devops

#45 Termo de Abertura do Projeto
  docs/Termo-Abertura-Projeto.md
Labels: EPS, documentation

#46 Protótipo de Baixa Fidelidade
  docs/imagens/low_fidelity_prototype/Component 1.png
  docs/imagens/low_fidelity_prototype/Component 2.png
  docs/imagens/low_fidelity_prototype/Component 3.png
  docs/imagens/low_fidelity_prototype/Component 4.png
  docs/mds/Protótipo_de_baixa_fidelidade.md
Labels: MDS, documentation, technical

#51 US01 - Leitura de Letras
  public/index.html
  src/App.vue
  vue.config.js
Labels: MDS, new feature

#52 Configurar deploy contínuo
  .gitignore
  .gitlab-ci.yml
  netlify.toml
  package.json
Labels: EPS, devops
