Repository fga-eps-mds/2019.2-ArBC, pull requests merged in 2019-11, with the labels that each got.

#107 Aperfeiçoamento da interface gráfica
  public/favicon.ico
  src/components/Home.vue
  src/components/HomeCard.vue
  src/components/ToolBar.vue
  src/vue_material/components.ts
Labels: MDS, enhancement

#109 Feature/#12 show image
  src/components/Camera.vue
  src/services/wordsStats.ts
  src/store/models.d.ts
Labels: MDS, new feature

#114 Adicionar arquivo env de produção
  .env.production
  package-lock.json
Labels: MDS, technical

#127 Error cobertura de código
  .coveralls.yml
  .gitlab-ci.yml
  README.md
  arquivo-test
  package.json
Labels: EPS, bug, devops

#125 Adicionar ícone do app
  public/favicon.ico
  public/img/icons/android-chrome-192x192.png
  public/img/icons/android-chrome-512x512.png
  public/img/icons/apple-touch-icon-120x120.png
  public/img/icons/apple-touch-icon-152x152.png
  public/img/icons/apple-touch-icon-180x180.png
  public/img/icons/apple-touch-icon-60x60.png
  public/img/icons/apple-touch-icon-76x76.png
  public/img/icons/apple-touch-icon.png
  public/img/icons/favicon-16x16.png
  public/img/icons/favicon-32x32.png
  public/img/icons/msapplication-icon-144x144.png
  public/img/icons/mstile-150x150.png
  public/img/icons/safari-pinned-tab.svg
  public/manifest.json
  src/assets/logo.png
Labels: MDS, enhancement

#123 Atualização do readme
  README.md
Labels: EPS, documentation, technical

#133 Como Contribuir na devel
  CONTRIBUTING.md
Labels: EPS, bug, documentation, scrum master

#134 Post Mortem
  Postmortem.md
Labels: EPS, MDS, documentation, release

#136 Update pipeline
  .gitlab-ci.yml
  README.md
Labels: EPS, devops

#132 Aprimoramento na documentação de MDS
  docs/imagens/documento_de_arquitetura/Diagrama_Caso_Uso_ArBC.jpeg
  docs/imagens/documento_de_arquitetura/Diagrama_de_Pacotes.jpeg
  docs/imagens/documento_de_arquitetura/Diagrama_de_Pacotes_Back.jpeg
  docs/imagens/documento_de_arquitetura/Diagrama_de_Pacotes_Front.jpeg
  docs/imagens/prototipo_de_alta_fidelidade/Component 1.png
  docs/imagens/prototipo_de_alta_fidelidade/Component 2.png
  docs/imagens/prototipo_de_alta_fidelidade/Component 3.png
  docs/imagens/prototipo_de_alta_fidelidade/Component 4.png
  docs/mds/Documento_de_arquitetura.md
  docs/mds/Protótipo_de_alta_fidelidade.md
  src/store/models.d.ts
Labels: MDS, architect, documentation

#137 Update docs
  docs/eps/roadmapDevops.md
  docs/policies/continuous_delivery.md
  docs/policies/quality.md
Labels: EPS, devops

#142 Mudar cor do tema da aplicação e URL de início da PWA inexistente
  public/manifest.json
  src/components/Home.vue
  src/router.ts
Labels: MDS, bug, enhancement

#143 Manual do Usuário Finalizado
  docs/imagens/manual_do_usuario/Home.jpg
  docs/imagens/manual_do_usuario/HomeGuiada.jpg
  docs/imagens/manual_do_usuario/MARKER TREM.jpg
  docs/imagens/manual_do_usuario/TREM.jpg
  docs/imagens/manual_do_usuario/TREM_GIF.jpg
  docs/mds/Manual_do_usuario.md
Labels: MDS, documentation, good first issue

#144 Documento de Testes de usabilidade
  docs/usabilidade.md
Labels: MDS, documentation

#145 Testes da câmera e dos outros componentes
  README.md
  dist/css/chunk-28fc7f00.87676a32.css
  dist/index.html
  dist/js/app.9ca42e92.js
  dist/js/app.9ca42e92.js.map
  dist/js/chunk-28fc7f00.1e669474.js
  dist/js/chunk-28fc7f00.1e669474.js.map
  dist/js/chunk-2d0e5e97.8da20a97.js
  dist/js/chunk-2d0e5e97.8da20a97.js.map
  dist/js/chunk-c2e4a3e6.94dcd10b.js
  dist/js/chunk-c2e4a3e6.94dcd10b.js.map
  dist/js/chunk-vendors.22ac635c.js
  dist/js/chunk-vendors.22ac635c.js.map
  dist/manifest.json
  dist/precache-manifest.4d09f96a27203b1e61da72e2dd9a4eb3.js
  dist/service-worker.js
  package-lock.json
  package.json
  src/components/HomeCard.vue
  src/store/modules/letters.ts
  tests/unit/App.spec.ts
  tests/unit/Camera.spec.ts
  tests/unit/HomeCard.spec.ts
  tests/unit/HowToUseModal.spec.ts
  tests/unit/NotFound.spec.ts
  tests/unit/NotFoundView.spec.ts
  tests/unit/ToolBar.spec.ts
  tests/unit/__mocks__/AMarker.vue
  tests/unit/__mocks__/Entity.vue
  tests/unit/helpers/generateFakeData.ts
  tests/unit/helpers/types.d.ts
Labels: MDS, bug, enhancement, technical

#148 Refatorando código do app e tipando funções
  dist/css/chunk-2c844006.09aee35b.css
  dist/index.html
  dist/js/app.9cff49d5.js
  dist/js/app.9cff49d5.js.map
  dist/js/chunk-2c844006.7387e497.js
  dist/js/chunk-2c844006.7387e497.js.map
  dist/js/chunk-2d0e5e97.1d43811e.js
  dist/js/chunk-2d0e5e97.1d43811e.js.map
  dist/js/chunk-c2e4a3e6.3ac6d4fa.js
  dist/js/chunk-c2e4a3e6.3ac6d4fa.js.map
  dist/js/chunk-vendors.605424f7.js
  dist/js/chunk-vendors.605424f7.js.map
  dist/precache-manifest.c46a144d4df70671bf40a303111a489a.js
  dist/service-worker.js
  src/App.vue
  src/components/Camera.vue
  src/components/HomeCard.vue
  src/components/HowToUseModal.vue
  src/components/NotFound.vue
  src/components/ToolBar.vue
  src/services/api.ts
  src/services/markersStats.ts
  src/services/wordsStats.ts
  src/store/modules/letters.ts
  src/store/modules/words.ts
  src/views/NotFound.vue
  tests/unit/LettersModule.spec.ts
Labels: MDS, enhancement, technical

#150 Wiki Release 2
  docs/EVM.md
  docs/Postmortem.md
  docs/gqm.md
  docs/policies/continuous_delivery.md
  docs/sprints/Fechamento-Sprint-12.md
Labels: EPS, documentation

#152 Atualizar badge da cobertura de codigo no README
  README.md
Labels: MDS, enhancement

#153 Release v.2.0.1
  README.md
Labels: release
