Repository fga-eps-mds/2019.2-ArBC, pull requests merged in 2019-10, with the labels that each got.

#53 Melhorias e correções no documento de arquitetura
  docs/imagens/documento_de_arquitetura/Diagrama_Relações.jpeg
  docs/imagens/documento_de_arquitetura/Diagrama_de_Pacotes.jpeg
  docs/mds/Documento_de_arquitetura.md
Labels: MDS, documentation

#54 Backlog de Produto
  docs/Product-Backlog.md
Labels: EPS, documentation, product owner

#63 Correção de bug do deploy contínuo
  .gitlab-ci.yml
Labels: EPS, bug, devops

#64 Feature/#api integration
  .env.development
  package-lock.json
  src/services/api.ts
Labels: architect, bug

#68 Correções no Documento de Visão
  docs/mds/Documento_de_visao.md
Labels: MDS, documentation

#58 Plano de Comunicação
  docs/Plano-Comunicacao.md
Labels: EPS, documentation, scrum master

#66 Correções na leitura de letra
  public/index.html
  src/App.vue
  src/components/Camera.vue
  src/router.ts
  src/views/Home.vue
Labels: MDS, technical

#71 Marcadores com nome errado
  AR_markers/marker_images/pattern-A.png
  AR_markers/marker_images/pattern-B.png
  AR_markers/marker_images/pattern-C.png
  AR_markers/marker_images/pattern-D.png
  AR_markers/marker_images/pattern-E.png
  AR_markers/marker_images/pattern-F.png
  AR_markers/marker_images/pattern-G.png
  AR_markers/marker_images/pattern-H.png
  AR_markers/marker_images/pattern-I.png
  AR_markers/marker_images/pattern-J.png
  AR_markers/marker_images/pattern-K.png
  AR_markers/marker_images/pattern-L.png
  AR_markers/marker_images/pattern-M.png
  AR_markers/marker_images/pattern-N.png
  AR_markers/marker_images/pattern-O.png
  AR_markers/marker_images/pattern-P.png
  AR_markers/marker_images/pattern-Q.png
  AR_markers/marker_images/pattern-R.png
  AR_markers/marker_images/pattern-S.png
  AR_markers/marker_images/pattern-T.png
  AR_markers/marker_images/pattern-U.png
  AR_markers/marker_images/pattern-V.png
  AR_markers/marker_images/pattern-W.png
  AR_markers/marker_images/pattern-X.png
  AR_markers/marker_images/pattern-Y.png
  AR_markers/marker_images/pattern-Z.png
Labels: MDS, bug

#57 Roadmaps
  docs/eps/roadmap.md
  docs/eps/roadmapDevops.md
  docs/eps/roadmapProductOwner.md
  docs/eps/roadmapScrumMaster.md
Labels: EPS, documentation

#59 Documento de Gerenciamento de Riscos
  docs/Plano-Gerenciamento-Riscos.md
Labels: EPS, documentation, scrum master

#73 Refatorar Documento de Arquitetura
  docs/mds/Documento_de_arquitetura.md
Labels: MDS, architect, bug, documentation

#78 Planejamento e Fechamento Sprint 5
  docs/sprints/Fechamento-Sprint-4.md
  docs/sprints/Fechamento-Sprint-5.md
  docs/sprints/Planejamento-Sprint-5.md
Labels: EPS, documentation, scrum master

#80 Readme update
  README.md
Labels: EPS, documentation

#86 Diagrama de caso de uso corrigido
  docs/imagens/documento_de_arquitetura/Diagrama_Caso_Uso_ArBC.jpeg
Labels: MDS, technical

#94 Changing node_modules folder permission
  Dockerfile
Labels: MDS, bug, enhancement, technical

#92 Correção dos gifs transparentes
  public/img/icons/favicon-16x16.png
  public/img/icons/favicon-32x32.png
  public/index.html
  src/App.vue
Labels: MDS, bug

#90 Aprimoramento no Diagrama de Pacotes
  docs/imagens/documento_de_arquitetura/Diagrama_de_Pacotes.jpeg
Labels: MDS, technical

#98 Documento de como funciona o produto #96
  docs/imagens/funcionamento_do_produto/A_marker.jpg
  docs/imagens/funcionamento_do_produto/B_marker.jpg
  docs/imagens/funcionamento_do_produto/L_marker.jpg
  docs/imagens/funcionamento_do_produto/O_marker.jpg
  docs/mds/Funcionamento_do_Produto.md
Labels: MDS, documentation

#99 Documento sobre o back e o front
  docs/mds/Interacoes_do_produto.md
Labels: MDS, documentation

#102 US02 - Identificar Palavra
  package-lock.json
  package.json
  src/App.vue
  src/services/markersStats.ts
  src/services/types.d.ts
Labels: MDS, new feature

#100 Interface gráfica finalizada
  package-lock.json
  package.json
  public/index.html
  src/App.vue
  src/assets/ArBC_logo.png
  src/assets/arara.svg
  src/assets/github.svg
  src/assets/github_gray.svg
  src/components/Camera.vue
  src/components/Home.vue
  src/components/HomeCard.vue
  src/components/ToolBar.vue
  src/main.ts
  src/router.ts
  src/views/About.vue
  src/views/Camera.vue
  src/views/Home.vue
  src/vue_material/components.ts
  src/vue_material/types.d.ts
Labels: MDS, enhancement, new feature

#103 Feature/#11 word validation
  src/components/Camera.vue
  src/services/api.ts
  src/store/models.d.ts
  src/store/modules/words.ts
Labels: MDS, new feature

#105 Melhorando as tipagens dos objetos
  src/components/Camera.vue
  src/store/models.d.ts
  src/store/modules/letters.ts
  src/store/modules/words.ts
Labels: MDS, enhancement, technical
